### ISSUE TITLE
Weird Interaction With MouseKeys

### ISSUE THREAD

**Issue by treed** [keyboardio/Kaleidoscope-ShapeShifter#3]
I'm trying to cause shift+mousedirection to be scrolling.

The shapeshifter config is here: https://github.com/treed/Model01-Firmware/blob/master/Model01-Firmware.ino#L179-L185

For some reason, when done in this way (rather than directly as a key), scroll up is the same as scroll left and scroll down is the same as scroll right, so I can only do horizontal scrolling.

Because it works fine directly in the keymap, I suspect the problem is in ShapeShifter, but maybe I'm just doing something wrong?

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#410.
